import Configuration
import Foundation
import Shared

/// Since Xcode 27, SwiftUI's `@State` is a macro rather than a property wrapper. The macro expands into implicit peer
/// declarations: the projected value (`$name`), the backing storage (`_name` and `__name`), and a static property
/// holding the initial value.
///
/// Reads of the projected value and backing storage are references to the peers rather than the state property
/// itself, so those references are attributed to the state property. Implicit declarations are also retained, which
/// would cause declarations referenced only by the initial value of an otherwise unused state property to also be
/// retained, so the peers and the generated accessors of the state property are unretained.
final class SwiftUIStateMacroReferenceBuilder: SourceGraphMutator {
    private static let stateMacroUsr = "s:7SwiftUI5Stateyycfm"

    private let graph: SourceGraph

    required init(graph: SourceGraph, configuration _: Configuration, swiftVersion _: SwiftVersion) {
        self.graph = graph
    }

    func mutate() {
        for property in graph.declarations(ofKind: .varInstance) {
            guard !property.isImplicit,
                  property.references.contains(where: { $0.declarationKind == .macro && $0.usr == Self.stateMacroUsr }),
                  let parent = property.parent
            else { continue }

            let peers = peerDeclarations(of: property, in: parent)
            let peerDecls = peers.flatMapSet { $0.descendentDeclarations.union([$0]) }

            // The property accessors are also generated by the macro, and reference the backing storage.
            for decl in peerDecls.union(property.declarations) {
                graph.unmarkRetained(decl)
            }

            // The implicit memberwise initializer assigns the backing storage, which would otherwise cause it to be
            // used regardless of whether the state property is used.
            for decl in peerDecls {
                for reference in graph.references(to: decl) {
                    guard let referenceParent = reference.parent,
                          referenceParent.kind == .functionConstructor,
                          referenceParent.isImplicit
                    else { continue }

                    graph.remove(reference)
                }
            }

            let accessiblePeerNames = ["$\(property.name)", "_\(property.name)"]

            for peer in peers where accessiblePeerNames.contains(peer.name) {
                buildReferences(to: property, from: peer)
            }
        }
    }

    // MARK: - Private

    private func peerDeclarations(of property: Declaration, in parent: Declaration) -> Set<Declaration> {
        // All peers are located at the macro attribute, identify the location via the backing storage peer.
        guard let backingStorage = parent.declarations.first(where: {
            $0.isImplicit && $0.kind == .varInstance && $0.name == "_\(property.name)"
        }) else { return [] }

        return parent.declarations.filter {
            $0.isImplicit && $0.kind.isVariableKind && $0.location == backingStorage.location
        }
    }

    private func buildReferences(to property: Declaration, from peer: Declaration) {
        // Only reads are attributed to the state property, e.g. assigning the backing storage in an initializer is not
        // a use of the state property.
        guard let getter = peer.declarations.first(where: { $0.kind == .functionAccessorGetter }) else { return }

        let peerReferences = graph.references(to: getter)

        for peerReference in peerReferences {
            // References from within the macro expansion are implicit.
            guard let referenceParent = peerReference.parent, !referenceParent.isImplicit else { continue }

            for usr in property.usrs {
                let reference = Reference(
                    name: property.name,
                    kind: .normal,
                    declarationKind: property.kind,
                    usr: usr,
                    location: peerReference.location
                )
                reference.parent = referenceParent
                graph.add(reference, from: referenceParent)
            }
        }
    }
}
